@echo off

IF NOT EXIST lastrev.txt (
    echo Unknown Revision > lastrev.txt
)

FOR /F %%H IN (lastrev.txt) DO SET LASTREVISION=%%H

IF EXIST "C:\Program Files\Git\bin\git.exe" (
    SET FOUNDGIT="C:\Program Files\Git\bin\git.exe"
) ELSE IF EXIST "C:\Program Files (x86)\Git\bin\git.exe" (
    SET FOUNDGIT="C:\Program Files (x86)\Git\bin\git.exe"
) ELSE IF EXIST "%PROGRAMFILES%\Git\bin\git.exe" (
    SET FOUNDGIT="%PROGRAMFILES%\Git\bin\git.exe"
) ELSE IF EXIST "%PROGRAMFILES(x86)%\Git\bin\git.exe" (
    SET FOUNDGIT="%PROGRAMFILES(x86)%\Git\bin\git.exe"
) ELSE (
    goto exit
)

%FOUNDGIT% rev-list HEAD --count > lastrev.txt

FOR /F %%H IN (lastrev.txt) DO SET REVISION=%%H

echo Current revision is %REVISION%
echo Last revision is %LASTREVISION%

IF %REVISION% NEQ %LASTREVISION% (
    echo // generated by gitrev.cmd > ..\..\steam_api\buildnumber.h
    echo #define BUILDNUMBER %REVISION% >> ..\..\steam_api\buildnumber.h
    echo #define BUILDNUMBER_STR "%REVISION%" >> ..\..\steam_api\buildnumber.h
    echo #define BUILDHOST "%COMPUTERNAME%" >> ..\..\steam_api\buildnumber.h
)
copy /y "lastrev.txt" "D:\eldorstuff\iw4play-rev\production\updater-cache\lastrev.txt"

goto exit

:exit